# Generated by Django 5.2.4 on 2025-07-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='contact',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
    ]
