# Generated by Django 5.2.4 on 2025-07-27 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_hospital_alter_customuser_role_appointment_hospital_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Hospital', 'verbose_name_plural': 'Hospitals'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='patientvisit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.hospital'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='assigned_by',
            field=models.ForeignKey(limit_choices_to={'role': 'receptionist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radiologyrequest',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.hospital'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'time')},
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('hospital', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('hospital', 'name')},
        ),
    ]
