# Generated by Django 5.2.4 on 2025-08-25 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_patient_address_alter_patient_phone_number_labreport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='note',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='billing.patient'),
        ),
    ]
