# Generated by Django 5.2.4 on 2025-08-25 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rename_note_medicalrecord_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labreport',
            old_name='created_at',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='labreport',
            name='lab_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='test_name',
            field=models.CharField(max_length=200),
        ),
    ]
