# Generated by Django 5.2.4 on 2025-08-28 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_rename_created_at_labreport_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiologyreport',
            old_name='findings',
            new_name='report',
        ),
        migrations.AlterField(
            model_name='radiologyreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.patient'),
        ),
        migrations.AlterField(
            model_name='radiologyreport',
            name='radiologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
