# Generated by Django 5.2.4 on 2025-09-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_rename_findings_radiologyreport_report_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
