# Generated by Django 5.2.4 on 2025-09-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='prescribed_medicines',
            field=models.ManyToManyField(blank=True, related_name='medical_records', to='billing.medicine'),
        ),
    ]
