# Generated by Django 5.2.4 on 2025-09-30 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_medicalrecord_prescribed_medicines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(default=1, help_text='E.g. 500mg twice daily', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(default='N/A', help_text='E.g. 7 days', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True, help_text='Special instructions', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='billing.medicine'),
            preserve_default=False,
        ),
    ]
