# Generated by Django 5.2.4 on 2025-09-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_prescription_medicines_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(default='No special instructions'),
        ),
    ]
