# Generated by Django 5.2.4 on 2025-10-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(max_length=255),
        ),
    ]
