# Generated by Django 5.2.4 on 2025-11-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_prescription_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='medicine',
            new_name='medicines',
        ),
    ]
