# Generated by Django 5.2.4 on 2025-11-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_rename_medicine_prescription_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.TextField(),
        ),
    ]
