# Generated by Django 5.2.4 on 2025-11-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_alter_prescription_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dispensed_notes',
            field=models.TextField(blank=True, help_text='Optional: Record of what was actually dispensed', null=True),
        ),
    ]
