# Generated by Django 5.2.4 on 2025-11-28 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_stocklog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patientvisit',
            options={},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='invoice_no',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='lab_technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'lab'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_diagnosis', 'Under Diagnosis'), ('lab_requested', 'Lab Requested'), ('lab_completed', 'Lab Completed'), ('radiology_requested', 'Radiology Requested'), ('radiology_completed', 'Radiology Completed'), ('prescribed', 'Prescribed'), ('completed', 'Completed')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dispensed_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radiologyrequest',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_tests_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='radiologyrequest',
            name='radiologist',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'radiologist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_tests_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.hospital')),
            ],
            options={
                'unique_together': {('hospital', 'name')},
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.medicinecategory'),
        ),
    ]
