# Generated by Django 5.2.4 on 2025-12-09 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_bill_options_alter_hospital_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('pulse', models.PositiveIntegerField(null=True)),
                ('respiratory_rate', models.PositiveIntegerField(null=True)),
                ('systolic', models.PositiveIntegerField(null=True)),
                ('diastolic', models.PositiveIntegerField(null=True)),
                ('spo2', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.patientvisit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
