# Generated by Django 5.2.4 on 2025-12-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_vitalsign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsign',
            name='diastolic',
        ),
        migrations.RemoveField(
            model_name='vitalsign',
            name='pulse',
        ),
        migrations.RemoveField(
            model_name='vitalsign',
            name='systolic',
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='blood_pressure_diastolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='blood_pressure_systolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='spo2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
