# Generated by Django 5.2.4 on 2025-12-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_remove_vitalsign_diastolic_remove_vitalsign_pulse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='note_type',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
